name: Continuous integration

on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Create npm configuration
      run: echo "//npm.pkg.github.com/:_authToken=${token}" >> .npmrc
      env:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: "npm ci"
      run: npm ci

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test
